//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KroMusicEntities : DbContext
    {
        public KroMusicEntities()
            : base("name=KroMusicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FavoriteMusic> FavoriteMusic { get; set; }
        public virtual DbSet<FavoritePlaylist> FavoritePlaylist { get; set; }
        public virtual DbSet<LikeMusic> LikeMusic { get; set; }
        public virtual DbSet<LikePlaylist> LikePlaylist { get; set; }
        public virtual DbSet<Music> Music { get; set; }
        public virtual DbSet<MusicComment> MusicComment { get; set; }
        public virtual DbSet<MusicType> MusicType { get; set; }
        public virtual DbSet<Playlist> Playlist { get; set; }
        public virtual DbSet<PlaylistComment> PlaylistComment { get; set; }
        public virtual DbSet<PlaylistItem> PlaylistItem { get; set; }
        public virtual DbSet<PlaylistType> PlaylistType { get; set; }
        public virtual DbSet<Singer> Singer { get; set; }
        public virtual DbSet<SingerAttention> SingerAttention { get; set; }
        public virtual DbSet<SubType> SubType { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserAttention> UserAttention { get; set; }
    }
}
