//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusicComment()
        {
            this.MusicComment1 = new HashSet<MusicComment>();
            this.MusicComment11 = new HashSet<MusicComment>();
        }
    
        public int Id { get; set; }
        public int MusicId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> TargetId { get; set; }
        public string Content { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> ReplyId { get; set; }
        public bool Visited { get; set; }
    
        public virtual Music Music { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicComment> MusicComment1 { get; set; }
        public virtual MusicComment MusicComment2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicComment> MusicComment11 { get; set; }
        public virtual MusicComment MusicComment3 { get; set; }
        public virtual User User { get; set; }
    }
}
