//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Playlist()
        {
            this.FavoritePlaylist = new HashSet<FavoritePlaylist>();
            this.LikePlaylist = new HashSet<LikePlaylist>();
            this.PlaylistItems = new HashSet<PlaylistItems>();
            this.PlaylistType = new HashSet<PlaylistType>();
        }
    
        public int Id { get; set; }
        public int Likes { get; set; }
        public int OwnerId { get; set; }
        public bool IsPublic { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int PlayTimes { get; set; }
        public string Cover { get; set; }
        public string Name { get; set; }
        
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoritePlaylist> FavoritePlaylist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikePlaylist> LikePlaylist { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistItems> PlaylistItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistType> PlaylistType { get; set; }
    }
}
